### ISSUE TITLE
关于alist更新的问题

### ISSUE THREAD

**Issue by chenyong0709** [studylessshape/studylessshape.github.io#1]
以下是alist官方的方案
```
安装
curl -fsSL "https://alist.nn.ci/v3.sh" | bash -s install
更新
curl -fsSL "https://alist.nn.ci/v3.sh" | bash -s update
卸载
curl -fsSL "https://alist.nn.ci/v3.sh" | bash -s uninstall
```
但是我没root的手机提示这个，是不是没有root的手机不能一键更新？
![image](https://github.com/studylessshape/studylessshape.github.io/assets/97508075/49d79dd8-f88c-4dbf-a11a-e590e82c2290)

**Comment by studylessshape** [comment]
termux的包仓库有alist。按照官网的说法，你需要先查看一下alist的版本：
```
alist version
```
#### 如果是*v2*版本
先卸载alist：
```
pkg uninstall alist
```
然后再安装alist：
```
pkg install alist
```

#### 如果是*v3*版本
直接更新就行：
```
pkg update
pkg upgrade alist
```

**Comment by studylessshape** [comment]
> 

需要注意，卸载重装需要重新配置alist

**Comment by chenyong0709** [comment]
@studylessshape 
这两个命令我都输入了。我
pkg update
pkg upgrade alist
官方刚刚更新的版本，是3.22.0
我手机termux安装的是3.21.0
是不是termux包会慢一些？暂时更新不了？

**Comment by studylessshape** [comment]
> @studylessshape 这两个命令我都输入了。我 pkg update pkg upgrade alist 官方刚刚更新的版本，是3.22.0 我手机termux安装的是3.21.0 是不是termux包会慢一些？暂时更新不了？

是的，会慢一些
