### ISSUE TITLE
讨论与学习

### ISSUE THREAD

**Issue by ZiHao256** [studylessshape/studylessshape.github.io#1]
博主好，看到您关于actix-web和vue的博客和在线论坛，感觉很有意思，然后我最近也在学Rust，想基于actix-web和Vue做一个系统，可以加下好友讨论嘛？

**Comment by studylessshape** [comment]
可以，但其实我会的也不多

**Comment by ZiHao256** [comment]
> 可以，但其实我会的也不多

好的，谢谢哥。这是我的微信号：ZiHao_M256
