### ISSUE TITLE
运行alist如何保活？

### ISSUE THREAD

**Issue by chenyong0709** [studylessshape/studylessshape.github.io#2]
现在只能手动运行alist server 保持运行状态，只要退出，alist前端就访问不了了。
有没有可以跟官方一样的这种进程守护的方法吗？
![image](https://github.com/studylessshape/studylessshape.github.io/assets/97508075/ed98d366-e3d8-4010-9666-7b9a5dabe5e8)

**Comment by studylessshape** [comment]
termux弄起来挺麻烦的。

真要弄这个建议还是直接linux上弄好点

**Comment by chenyong0709** [comment]
好吧。不折腾了。就最原始的吧。
